- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
   - name: im going to install apache
     yum:
      name: "{{ item }}"
      state: present
  with_items:
     - mysql
     - php
     - unzip